### PR TITLE
Landscape v2 cleanup

### PR DESCRIPTION
**Pull request by tegioz**
This PR removes some files no longer needed after the migration to landscape v2.

In addition to the files removed by this PR, there are some more that landscape v2 doesn't need, but we haven't removed them as they could be used by some other processes (/cc @jmertic). Please review the list below for some extra cleaning:

- `.pre-commit-config.yaml`
- `config.yml`
- `missing.csv`
- Landscape v2 only uses the `lf_decentralized_trust_landscape.svg` file inside the images directory.

### CODE REVIEW

**Comment by jmertic** [comment]
`missing.csv` can be deleted. 

`config.yml` is used for the configuration of the lfx-landscape-tools integration.

Let's leave `.pre-commit-config.yaml` for now, but I do need to review and strip out the linters that aren't relevant.

**Comment by tegioz** [comment]
Thanks @jmertic, `missing.csv` deleted.

**Comment by tegioz** [comment]
@minyu66 could you remove the `deploy/netlify` check from the branch protection settings? I've paused the Netlify preview deployment, so the check won't pass anymore. Also, it'd be great if you could add the `validate` workflow Cintia added recently as a required one 🙂

Thanks!

**Comment by ryjones** [comment]
@tegioz if you can't merge this I will

**Comment by tegioz** [comment]
No, I can't. Thanks!

Could you also please update the branch protection settings? (remove the netlify check and require the validate one) 🙂

**Pull request merged**
